<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Coordinated Universal Time">
<General productName="Vugen" productVer="12" os="" host="WIN-BSQHK0F5KFL"><DocLocation><![CDATA[C:\Work\Performance\CORE\APA-ProcessFlow]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[APA-ProcessFlow]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[Init]]></AName>
<Summary sTime="1/4/2018 - 7:11:34" eTime="1/4/2018 - 7:11:34" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[Init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to qa.dxc-apa.net was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:11:35]]></Time>
<TimeTick>1515049895</TimeTick>
<NodeArgs eType="General" icon="0" nRep="9" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Wait for Email Address textbox was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:11:35]]></Time>
<TimeTick>1515049895</TimeTick>
<NodeArgs eType="General" icon="0" nRep="10" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4.1: Click on Email Address textbox was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:11:46]]></Time>
<TimeTick>1515049906</TimeTick>
<NodeArgs eType="General" icon="0" nRep="11" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[4.2: Type admin1@hpe.com in Email Address textbox was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:11:50]]></Time>
<TimeTick>1515049910</TimeTick>
<NodeArgs eType="General" icon="0" nRep="12" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[4.3: Type ******** in Password passwordbox was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:11:53]]></Time>
<TimeTick>1515049913</TimeTick>
<NodeArgs eType="General" icon="0" nRep="13" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4.4: Click on Login button was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:11:54]]></Time>
<TimeTick>1515049914</TimeTick>
<NodeArgs eType="General" icon="0" nRep="14" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[4.5: Wait for Good day, JavaScript link was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:11:55]]></Time>
<TimeTick>1515049915</TimeTick>
<NodeArgs eType="General" icon="0" nRep="15" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Click on Process Discovery  was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:12:07]]></Time>
<TimeTick>1515049927</TimeTick>
<NodeArgs eType="General" icon="0" nRep="16" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[7: Wait for processList_genericCompany  was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:12:07]]></Time>
<TimeTick>1515049927</TimeTick>
<NodeArgs eType="General" icon="0" nRep="17" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[9: Click on processList_genericCompany  was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:12:19]]></Time>
<TimeTick>1515049939</TimeTick>
<NodeArgs eType="General" icon="0" nRep="18" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[11: Wait for processName combobox was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:12:19]]></Time>
<TimeTick>1515049939</TimeTick>
<NodeArgs eType="General" icon="0" nRep="19" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[13: Click on processName combobox was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:12:32]]></Time>
<TimeTick>1515049952</TimeTick>
<NodeArgs eType="General" icon="0" nRep="20" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[14: Wait for Selected  was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:12:32]]></Time>
<TimeTick>1515049952</TimeTick>
<NodeArgs eType="General" icon="0" nRep="21" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[17: Click on Go button was finished]]></Details>
<Time><![CDATA[1/4/2018 - 7:12:44]]></Time>
<TimeTick>1515049964</TimeTick>
<NodeArgs eType="General" icon="0" nRep="22" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/4/2018 - 7:11:34" eTime="1/4/2018 - 7:12:44" passed="14" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Passed" >
<Disp><![CDATA[APA-ProcessFlow Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Action rID="T19">
<AName><![CDATA[End]]></AName>
<Summary sTime="1/4/2018 - 7:12:44" eTime="1/4/2018 - 7:12:44" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="25" >
<Disp><![CDATA[End Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="1/4/2018 - 7:11:32" eTime="1/4/2018 - 7:12:44" passed="14" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="4" status="Passed" >
<Disp><![CDATA[Test APA-ProcessFlow Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>